In [2]:
import numpy as np

In [11]:
a = np.random.random((2, 3, 5))
a

array([[[0.56268456, 0.37377541, 0.12196282, 0.84014432, 0.51920942],
        [0.74541628, 0.50396961, 0.48318888, 0.30726739, 0.10995831],
        [0.87225885, 0.97451648, 0.70318567, 0.27298702, 0.59198281]],

       [[0.0352719 , 0.73460421, 0.99876251, 0.84849142, 0.65224808],
        [0.35367286, 0.38452427, 0.85395186, 0.69598028, 0.8856841 ],
        [0.03167378, 0.67838264, 0.62435478, 0.40777556, 0.48517559]]])

In [12]:
a.shape
a.size

30

In [18]:
a[0,0,0] = 5
a

array([[[5.        , 0.37377541, 0.12196282, 0.84014432, 0.51920942],
        [0.74541628, 0.50396961, 0.48318888, 0.30726739, 0.10995831],
        [0.87225885, 0.97451648, 0.70318567, 0.27298702, 0.59198281]],

       [[0.0352719 , 0.73460421, 0.99876251, 0.84849142, 0.65224808],
        [0.35367286, 0.38452427, 0.85395186, 0.69598028, 0.8856841 ],
        [0.03167378, 0.67838264, 0.62435478, 0.40777556, 0.48517559]]])

In [20]:
mylist = ["cat", "dog"]

In [22]:
np.array(mylist)

array(['cat', 'dog'], dtype='<U3')

In [3]:
test = [4, 5, 6, 7, 8, 2, 4, 5, 6]
np.array(test)

array([4, 5, 6, 7, 8, 2, 4, 5, 6])

In [7]:
first = np.random.random((3, 4))
second = np.random.random((3, 4))
print(first)
print(second)

[[0.04593675 0.51686729 0.50191799 0.00852139]
 [0.09650984 0.86507818 0.34881756 0.27302812]
 [0.15705915 0.61293139 0.37493054 0.6514269 ]]
[[0.27984262 0.04042624 0.28746519 0.8454185 ]
 [0.58104057 0.95413737 0.48755889 0.84631006]
 [0.9937633  0.1427533  0.59757788 0.46220503]]


In [10]:
sum1 = np.add(first, second)
print(sum1)

[[0.32577936 0.55729353 0.78938318 0.85393989]
 [0.67755041 1.81921554 0.83637645 1.11933818]
 [1.15082245 0.75568469 0.97250842 1.11363194]]


In [11]:
first + second 

array([[0.32577936, 0.55729353, 0.78938318, 0.85393989],
       [0.67755041, 1.81921554, 0.83637645, 1.11933818],
       [1.15082245, 0.75568469, 0.97250842, 1.11363194]])