In [2]:
import numpy as np

In [11]:
a = np.random.random((2, 3, 5))
a

array([[[0.56268456, 0.37377541, 0.12196282, 0.84014432, 0.51920942],
        [0.74541628, 0.50396961, 0.48318888, 0.30726739, 0.10995831],
        [0.87225885, 0.97451648, 0.70318567, 0.27298702, 0.59198281]],

       [[0.0352719 , 0.73460421, 0.99876251, 0.84849142, 0.65224808],
        [0.35367286, 0.38452427, 0.85395186, 0.69598028, 0.8856841 ],
        [0.03167378, 0.67838264, 0.62435478, 0.40777556, 0.48517559]]])

In [12]:
a.shape
a.size

30

In [18]:
a[0,0,0] = 5
a

array([[[5.        , 0.37377541, 0.12196282, 0.84014432, 0.51920942],
        [0.74541628, 0.50396961, 0.48318888, 0.30726739, 0.10995831],
        [0.87225885, 0.97451648, 0.70318567, 0.27298702, 0.59198281]],

       [[0.0352719 , 0.73460421, 0.99876251, 0.84849142, 0.65224808],
        [0.35367286, 0.38452427, 0.85395186, 0.69598028, 0.8856841 ],
        [0.03167378, 0.67838264, 0.62435478, 0.40777556, 0.48517559]]])

In [20]:
mylist = ["cat", "dog"]

In [22]:
np.array(mylist)

array(['cat', 'dog'], dtype='<U3')

In [23]:
test = [4, 5, 6, 7, 8, 2, 4, 5, 6]
np.array(test)

array([4, 5, 6, 7, 8, 2, 4, 5, 6])