# Working with Numpy

Numpy is the numerical python package, with a lot of mathematical capabilities. Before we can use it, we need to first import the package. We will import it under the name np such that we can afterwards refer to it by this short name.

In [1]:
import numpy as np 

In the cell below, generate two 2x3 array with all elements equal to 1 - assign one of the arrays to the variable a and the other one to b. Add the two arrays. What do you get?

In [12]:
a = np.full((2,3), 1)
b = np.full((2,3), 1)
print(a)
print(b)
a + b
# I get 2 as a result of adding 1 +1 

[[1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]]


array([[2, 2, 2],
       [2, 2, 2]])

Now generate another array c which is a 3x2 array with all elements equal to 1. Are you able to add a and c? Why or why not?

In [14]:
c = np.full((3, 2), 1)
a + c
# No, because arrays don't have the same measurements 2x3 vs 3x2 

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

Transpose c so that it has the same structure of a (i.e. become a 2x3 array). Assign the transposed array to variable "d". Are you able to add a and d?

In [17]:
d = c.transpose()
d + a
#Yes it worked 

array([[2, 2, 2],
       [2, 2, 2]])

Which combination of arrays are you able to multiply with each other? Why?

In [19]:
z = np.full((3,5), 4)
y = np.full((2,3), 5)
z * y

# We can only multiply arrays that have the same shape, meaning (2x3)*(2x3);
# If we try to multiply an array smaller or bigger than that, we will get an error 
# ValueError: operands could not be broadcast together with shapes (3,5) (2,3) 

ValueError: operands could not be broadcast together with shapes (3,5) (2,3) 

Create a list which contains the numbers from 0 to 10. Square the list elementwise using numpy functions.

In [24]:
list1 = [0, 1, 2, 3, 4, 5, 6, 7, 8 , 9, 10]
np.square(list1)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

Create a numpy array of size 10x10 which has random numbers between 0 and 100 on the main diagonal and zeros otherwise.

In [26]:
array1 = np.random.random((10, 10))*100
array1

array([[44.81945133, 56.40822335, 66.03199494, 83.89210599, 76.38050285,
        86.78784985, 49.39015282, 92.88666841, 54.60497053, 30.3096442 ],
       [27.41759275, 95.16587682, 15.833521  , 47.35452612, 55.79511571,
        72.90010179, 11.76468049, 13.09913311, 94.54732411,  3.6257108 ],
       [35.79330989, 44.16081514, 77.35246674, 18.23277852, 51.26489377,
        89.98012708, 14.99037839, 42.06151668, 80.56376613, 77.08711243],
       [38.23244474,  5.52592873, 45.57082914, 67.16459521, 20.27735538,
        60.63938483, 85.01227795, 37.9482083 , 62.09086885, 71.23215368],
       [33.73539525, 49.73030181, 49.52701952, 32.83654169, 23.54367503,
        31.12325059, 46.64413942, 15.27435706, 36.41943404, 84.00573513],
       [75.07356556, 16.09458349,  9.65017401, 23.52880877, 67.4571349 ,
        16.80534058, 80.10829158, 50.6176927 , 37.32068951, 98.89800516],
       [56.91308911, 68.89583027,  8.1615331 , 56.22687699, 76.81919939,
        33.72621952, 38.98782635, 43.7347786 

In [1]:
David = "You Rock Gonz!"
print(David)

You Rock Gonz!
